### ISSUE TITLE
14 Apr - Resolve user unathorized access on Mongodb

### ISSUE THREAD

**Issue by Alyxhelpme** [13th-office/IBM-SkillBoard#26]
![Image](https://user-images.githubusercontent.com/74560600/231895585-99cf3fe1-a1c7-4a16-8fd1-ec1c93279b32.png)

Back end is already connected, however apparently user does not have the permissions to access database

**Comment by Alyxhelpme** [comment]
![Image](https://user-images.githubusercontent.com/74560600/231895862-392d0b37-c23d-4b3d-ad10-2c086b05be2c.png)

Terminal output

**Comment by gonzalpi** [comment]
Fixed by setting the following in `config/mongoid.yml`:
```yml

development:
  clients:
    default:
      options:
        roles:
          - 'readWrite'
        auth_mech: :scram
        auth_source: <DB_NAME>
```
